name: flutter_eapp
description: A new Flutter application.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1









environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: '>=1.12.13+hotfix.5 <2.0.0'


dependencies:
  flutter:
    sdk: flutter

  splashscreen:
  meta: ^1.0.5
  im_stepper: ^0.1.2+9
  collection: ^1.14.3
  google_fonts: ^0.3.5
  firebase_auth: ^0.18.3
  firebase_core:
  firebase_core_platform_interface: ^2.1.0
  cloud_functions_platform_interface: ^3.0.3
  cloud_functions_web: ^3.1.1
  cloud_firestore:
  fluttertoast: ^7.1.6
  modal_progress_hud: ^0.1.3
  provider: ^4.3.2+2
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^3.2.0
  get: ^3.22.2
  font_awesome_flutter: ^8.10.1
  country_pickers: ^1.3.0
  fancy_bottom_navigation: ^0.3.2
  page_transition: ^1.1.7+3
  hidden_drawer_menu: ^2.0.1
  rflutter_alert: ^1.1.0
  flutter_xlider: ^3.4.0
  intro_views_flutter: ^2.8.2
  bottom_navy_bar: ^5.6.0
  carousel_slider: ^1.3.0
  division: ^0.6.1
  flutter_icons: ^1.1.0
  sliding_up_panel: ^0.3.4
  carousel_pro: ^1.0.0
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.4.1
  intl: ^0.16.1
  expandable: ^4.1.4
  simple_animations: ^1.3.3
  firebase_storage:
  firebase_analytics: ^5.0.6
  image_picker: ^0.6.7+4
  firebase_picture_uploader: ^1.2.0
  firebase_storage_web: ^0.1.1+1
  firebase_storage_platform_interface: ^1.0.2
  quiver: ^2.1.3
  plugin_platform_interface: ^1.0.0
  item_selector: ^0.1.1
  favorite_button: ^0.0.3
  color: ^2.1.1
  location: ^3.0.0
  permission_handler: ^5.1.0+2
  geocoding: ^1.0.5
  flutter_swiper :
  flutter_staggered_grid_view: ^0.3.4
  parallax_swiper: ^0.0.1
  animated_splash_screen: ^1.0.1+2
  loading_animations: "^2.1.0"
  url_launcher:
  firebase_messaging:
  connectivity:
  flutter_custom_clippers: ^1.1.2
  sms_autofill:
  drawing_animation: ^0.1.3
  cupertino_stepper: ^0.2.0
  dio:
  email_validator: ^2.0.1
  flutter_colorpicker:
  hexcolor:
  path_provider:
  screen_size_test: ^1.0.0+1







  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - android/app/src/main/res/










    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
  fonts:
      - family: Pacifico
        fonts:
          - asset: assets/fonts/Pacifico-Regular.ttf
      - family: Tajawal
        fonts:
          - asset: assets/fonts/Tajawal-Black.ttf

